[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@src/=src/",
    "@test/=test/",
]
ffi = true
ast = true
build_info = true
optimizer-runs = 10_000
extra_output = ["storageLayout"]

[profile.production]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
optimizer-runs = 10_000

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer-runs = 10_000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
line_length = 80
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
